# Generated by Django 4.1 on 2024-06-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('normal', 'normal'), ('severe', 'severe'), ('critical', 'critical')], max_length=20),
        ),
    ]
