# Generated by Django 4.1 on 2024-06-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_backend', '0002_alter_alert_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('normal', 'normal'), ('critical', 'critical'), ('severe', 'severe')], max_length=20),
        ),
    ]
