# Generated by Django 4.1 on 2024-07-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_backend', '0005_alter_alert_date_alter_alert_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='category',
            field=models.CharField(choices=[('land', 'land'), ('atmosphere', 'atmosphere'), ('water', 'water'), ('earthquake', 'earthquake')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('severe', 'severe'), ('normal', 'normal'), ('critical', 'critical')], max_length=20),
        ),
    ]
